name: Newman Tests

on:
  push:
    

jobs:
  newman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Newman
        run: npm install -g newman
      - name: Run Newman tests
        run: newman run API.postman_collection.json -e Local.postman_environment.json